[env]

CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++
          
          
OPENSSL=${{ github.workspace }}/openssl_android #arm
OPENSSL_DIR=${{ github.workspace }}/openssl_android
OPENSSL_INCLUDE_DIR=${{ github.workspace }}/openssl_android/include
OPENSSL_LIB_DIR=${{ github.workspace }}/openssl_android
PKG_CONFIG_PATH=${{ github.workspace }}/openssl_android
          
ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR=${{ github.workspace }}/openssl_android/include
          
ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR=${{ github.workspace }}/openssl_android
          
PKG_CONFIG_ALLOW_CROSS_armv7_linux_androideabi=1
      
         
ANDROID_NDK_VERSION=25.1.8937393

OPENSSL_DIR=${{ github.workspace }}
API=21
DEBUG= true
