name: Linux CI

on:
  push:
    branches: [ TESTNET ]
  pull_request:
    branches: [ TESTNET ]
    
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  OPENSSL_VERSION: openssl-1.1.1l
  
  
jobs:
        
  build-linux:
    # Note: even though Android builds for another architecture than Linux, it can reuse downloaded crates (source code, maybe 'cargo check').
    
    #continue-on-error: ${{ matrix.rust == 'nightly' }}
    #strategy:
    #  matrix:
    #    rust: [stable]




    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: "Compile & install Openssl 1.1l"
        run: |
          sudo apt install make gcc -y
          wget  "https://www.openssl.org/source/${OPENSSL_VERSION}.tar.gz"
          tar -xzvf ${OPENSSL_VERSION}.tar.gz
          sudo apt remove openssl -y
          cd ${OPENSSL_VERSION}
          ./config --prefix=/opt/openssl --openssldir=/usr/local/ssl
          make
          make install




       # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          
      - name: "Linux compile"
        run: |
          # Linux
          RUST_BACKTRSCE=full cargo build --target x86_64-unknown-linux-gnu  --release
   
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: target/x86_64-unknown-linux-gnu/release/libalgodot.so
      - name: Download-content
        uses: actions/download-artifact@v2
        with: 
          name: linux
          
    
