name: Linux CI

on:
  push:
    branches: [ Godot-3.5-DEV ]

    
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  OPENSSL_VERSION: openssl-1.1.1l
  
  
jobs:
        
  build-linux:
    # Note: even though Android builds for another architecture than Linux, it can reuse downloaded crates (source code, maybe 'cargo check').
    
    #continue-on-error: ${{ matrix.rust == 'nightly' }}
    #strategy:
    #  matrix:
    #    rust: [stable]




    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy


       # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: "Compile & install Openssl 1.1l"
        run: |
          sudo apt install make gcc -y
          wget  "https://www.openssl.org/source/${OPENSSL_VERSION}.tar.gz"
          tar -xzvf ${OPENSSL_VERSION}.tar.gz
          
          cd ${OPENSSL_VERSION}
          ./config --prefix=/opt/openssl --openssldir=/usr/local/ssl
          make
          sudo make install

          # Copy out OpenSSL Libs

          ls -al
             
      - name: "Linux compile"
        run: |
          # Linux
          
           export OPENSSL=${{ github.workspace }}/${OPENSSL_VERSION}
           export OPENSSL_DIR=${{ github.workspace }}/${OPENSSL_VERSION}
           export OPENSSL_LIB_DIR=${{ github.workspace }}/${OPENSSL_VERSION}
           
           export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=${{ github.workspace }}/${OPENSSL_VERSION}
           
          
           RUST_BACKTRSCE=full cargo build --target x86_64-unknown-linux-gnu  --release
   
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: target/x86_64-unknown-linux-gnu/release/libalgodot.so
      - name: Download-content
        uses: actions/download-artifact@v2
        with: 
          name: linux
          
  Itch_io:
      runs-on: ubuntu-22.04
      needs: build-linux
      steps:
       - name: Download content
         uses: actions/download-artifact@v4
         with: 
           name: linux
  
       
       - name: Archive site content
         uses: thedoctor0/zip-release@master
         with:
            filename: site.zip
       
       - name: Butler Publish
         uses: manleydev/butler-publish-itchio-action@master
         env:
           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
           BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
           CHANNEL: linux
           ITCH_GAME: Algodot
           ITCH_USER: inhumanity-arts
           PACKAGE: ./site.zip
