name: WASM CI

on:
  push:
    branches: [ Godot-3.5-DEV ]
  schedule:
    # Documentation : https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
    
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  OPENSSL_VERSION: openssl-1.1.1l
  GDNATIVE: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gdnative-sys-0.11.3/godot_headers/gdnative
  
  
jobs:
        
  build-WASM:
    # Note: even though Android builds for another architecture than Linux, it can reuse downloaded crates (source code, maybe 'cargo check').
    
    #continue-on-error: ${{ matrix.rust == 'nightly' }}
    #strategy:
    #  matrix:
    #    rust: [stable]




    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install specific nightly for wasm builds
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2023-01-27
            override: true
            components: rustfmt, clippy
            target: wasm32-unknown-emscripten

      - name: "Setup for WASM compile"

        run: |
          cd /home/runner/work/algodot/algodot
          
          #Modify Cargo.toml for WASM

          sed -i '/^\[workspace\]/,/\]/ {
              r /dev/stdin
              d
          }' Cargo.toml << 'EOF'
          [package]
          name = "Algodot"
          version = "0.2.0"
          edition = "2021"
          
          [lib]
          crate-type = ["cdylib"]
          path = "algodot/src/algod/mod.rs"
          
          [dependencies]
          algonaut = { git = "https://github.com/manuelmauro/algonaut", rev = "75bce54" }
          algodot_abi = { path = "abi" }
          algodot_core = { path = "core" }
          algodot_macros = { path = "macros" }
          gdnative = { version = "0.11", features = ["async"] }
          
          [workspace]
          members = [
              "algodot",
              "macros"
          ]
          EOF


          # Check Toml file
          cat Cargo.toml && cd 
          sudo apt-get update -y
          sudo apt-get install llvm-dev libclang-dev clang g++-multilib gcc-multilib libc6-dev libc6-dev-arm64-cross
          
       # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      #- name: Run cargo check
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: check
          
      - name: "Compile & install Openssl 1.1l"
        run: |
          sudo apt install make gcc -y
          wget  "https://www.openssl.org/source/${OPENSSL_VERSION}.tar.gz"
          tar -xzvf ${OPENSSL_VERSION}.tar.gz
          
          cd ${OPENSSL_VERSION}
          ./config --prefix=/opt/openssl --openssldir=/usr/local/ssl
          make
          sudo make install
          
      - name: "WASM Setup"
        run: |
          # Linux Check Other Dependencies
          # Should Ideally Be done via CI Commands using actions@cargoV1
          # Install the specific version of Rust toolchain.
          rustup toolchain install nightly-2023-01-27

          # Add wasm32-unknown-emscripten target to this toolchain.
          rustup +nightly-2023-01-27 target add wasm32-unknown-emscripten

          # Check If Installed
          rustc +nightly --version --verbose
          emcc -v

           
      - name: "WASM compile"
        run: |
          # Linux
          
           export OPENSSL=${{ github.workspace }}/${OPENSSL_VERSION}
           export OPENSSL_DIR=${{ github.workspace }}/${OPENSSL_VERSION}
           export OPENSSL_LIB_DIR=${{ github.workspace }}/${OPENSSL_VERSION}
           
           #export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=${{ github.workspace }}/${OPENSSL_VERSION}
           export C_INCLUDE_PATH=$EMSDK/upstream/emscripten/cache/sysroot/include
          
           #RUST_BACKTRSCE=full cargo build --target wasm32-unknown-emscripten  --release
           RUST_BACKTRSCE=full cargo +nightly-2023-01-27 build --target=wasm32-unknown-emscripten --release
          
          
    
